### ISSUE TITLE
Finding matches to substrings of layer names

### ISSUE THREAD

**Issue by ricburton** [awt2542/Find-for-Framer#1]
This is a super handy module—thanks for writing it!

So right in my layers list I have:

```
rectangle1
...
rectangle50
```

When I go:

```
for layer in $find 'rectangle3'
     print layer
```

It will return `<Layer id:35 name:rectangle30 (10,900) 280x25>`. Is that intended? I am trying to get `rectangle3`.

Thanks!

**Comment by awt2542** [comment]
Hi! Yes - rectangle30 contains rectangle3, which is why you get a match. There's no support for "exact match" right now - but it's planned. You can use my other module, for now: 
https://github.com/awt2542/Layers-for-Framer

Try Layers.withName('rectangle3')

**Comment by awt2542** [comment]
Rewrote the module to support exact match among other things. Your example should now work correctly (just replace $find with Select) :)
