### ISSUE TITLE
Find doesn't work in for loops

### ISSUE THREAD

**Issue by blaineb** [awt2542/Find-for-Framer#5]
When trying to use the module in a for loop, it doesn't return the proper object

**Comment by awt2542** [comment]
thanks for the report! you mean when doing something like this?

```
for x in [0..3]
   print ƒ('btn')
```

**Comment by 77mckenna** [comment]
![screen shot 2016-07-14 at 9 35 02 pm](https://cloud.githubusercontent.com/assets/7947780/16861919/dd754eb8-4a0a-11e6-8073-1b4e25643574.png)

**Comment by awt2542** [comment]
Thanks! That's a bug in the online example. Should be fixed in the repo. 
I'll update the example project to include the bug fix. Is this the same issue you had @blaineb ?

Skickat från min iPhone

**Comment by 77mckenna** [comment]
![screen shot 2016-07-15 at 8 06 31 am](https://cloud.githubusercontent.com/assets/7947780/16875131/59e271f8-4a63-11e6-9503-6ffdc5d818ae.png)
Same issue using latest code, thanks.

**Comment by 77mckenna** [comment]
Well not the same but this was the original issue for me ...

**Comment by awt2542** [comment]
@77mckenna your backticks doesn't look right to me :/

**Comment by 77mckenna** [comment]
![screen shot 2016-07-15 at 9 20 49 am](https://cloud.githubusercontent.com/assets/7947780/16877419/8b26da74-4a6d-11e6-9c22-9cfa75695e78.png)

**Comment by awt2542** [comment]
copy paste the line where you print ƒƒ('btn_*') and replace the function call on line 36. you can see how the selector isn't a proper string.

**Comment by 77mckenna** [comment]
![screen shot 2016-07-15 at 9 25 24 am](https://cloud.githubusercontent.com/assets/7947780/16877524/2b55e580-4a6e-11e6-900d-b2fafb3f064a.png)

**Comment by 77mckenna** [comment]
wait i fixed the rest of them that did it!

**Comment by 77mckenna** [comment]
Thanks for your help! I took those lines from somewhere ... hm. Not sure where.

**Comment by awt2542** [comment]
could be medium that reformats them :)
