### ISSUE TITLE
getLayers is not a function

### ISSUE THREAD

**Issue by mnstefan** [awt2542/Find-for-Framer#6]
Hi there,
thanks for this great component.

Unfortunately I'm bumping into the error above as I try to use it.

`
_findAll — findModule.coffee:19TypeError: Framer.CurrentContext.getLayers is not a function. (In 'Framer.CurrentContext.getLayers()', 'Framer.CurrentContext.getLayers' is undefined)
`

This seems do be caused by `layers = Framer.CurrentContext.getLayers()` in line 19.

I have the most up to date framer lib, am I missing anything?

**Comment by awt2542** [comment]
thanks for the report! should be fixed now :)
