### ISSUE TITLE
Update appears to have broken functionality

### ISSUE THREAD

**Issue by sohlis** [awt2542/Find-for-Framer#7]
On the latest update of Framer (V73)

It looks like there was a change to `Framer.CurrentContext.getLayers()`

Running Find-for-Framer on an old project, I'm getting this error

```
TypeError: Framer.CurrentContext.getLayers is not a function. (In 'Framer.CurrentContext.getLayers()', 'Framer.CurrentContext.getLayers' is undefined)
```

😢 Anyone know a way of fixing?

**Comment by awt2542** [comment]
Hi! Thanks for the report. Did you try the latest version here on GitHub?
